# fly.toml app configuration file generated for ronny-tailscale-exit on 2023-05-08T23:53:45+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ronny-tailscale-exit"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  PORT = "41641"

[[services]]
  protocol = "udp"
  internal_port = 41641

  [[services.ports]]
    port = 41641
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
